n = int(input('Digite um valor: '))
dobro = (n * 2)
triplo = (n * 3)
raiz = (n ** (1/2))
print('O dobro de {} vale: {}, o triplo de {} vale: {} e a raiz de {} vale: {:.2f}.'.format(n, dobro, n, triplo, n, raiz))