nome = str(input('Digite seu nome completo: ')).strip()
n = nome.split()
print('Prazer em conhecê-lo! {}.'.format(nome))
print('Seu primeiro nome é: {}.'.format(n[0]))
print('Seu último nome é: {}.'.format(n[-1]))
